[project]
name = "fast-fibonacci"
version = "0.1.0"
authors = [{ name = "Ferdinand Keller", email = "ferdinand.keller@proton.me" }]
description = "Fast Fibonacci Comparison using GMP."
readme = "README.md"
requires-python = ">=3.13,<3.14"
dependencies = ["gmpy2>=2.2.1", "loguru>=0.7.2"]
